//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from CacheShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//BinLogReq strcut implement
type BinLogReq struct {
	Logfile   string `json:"logfile"`
	Seek      int64  `json:"seek"`
	LineCount int32  `json:"lineCount"`
	LogSize   int32  `json:"logSize"`
}

func (st *BinLogReq) resetDefault() {
}

//ReadFrom reads  from _is and put into struct.
func (st *BinLogReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = _is.Read_string(&st.Logfile, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_int64(&st.Seek, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.LineCount, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.LogSize, 4, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *BinLogReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require BinLogReq, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *BinLogReq) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.Write_string(st.Logfile, 1)
	if err != nil {
		return err
	}

	err = _os.Write_int64(st.Seek, 2)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.LineCount, 3)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.LogSize, 4)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *BinLogReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
