//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from CacheShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//BinLogCompPartRsp strcut implement
type BinLogCompPartRsp struct {
	Data    BinLogRsp `json:"data"`
	IsPart  bool      `json:"isPart"`
	PartNum int32     `json:"partNum"`
	IsEnd   bool      `json:"isEnd"`
}

func (st *BinLogCompPartRsp) resetDefault() {
}

//ReadFrom reads  from _is and put into struct.
func (st *BinLogCompPartRsp) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = st.Data.ReadBlock(_is, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_bool(&st.IsPart, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.PartNum, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_bool(&st.IsEnd, 4, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *BinLogCompPartRsp) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require BinLogCompPartRsp, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *BinLogCompPartRsp) WriteTo(_os *codec.Buffer) error {
	var err error

	err = st.Data.WriteBlock(_os, 1)
	if err != nil {
		return err
	}

	err = _os.Write_bool(st.IsPart, 2)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.PartNum, 3)
	if err != nil {
		return err
	}

	err = _os.Write_bool(st.IsEnd, 4)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *BinLogCompPartRsp) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
