//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from CacheShare.tars
package DCache

type DataType int32

const (
	//DataType_INT enum
	DataType_INT = 0
	//DataType_STR enum
	DataType_STR = 1
)
