//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//GetRangeListReq strcut implement
type GetRangeListReq struct {
	ModuleName   string `json:"moduleName"`
	MainKey      string `json:"mainKey"`
	Field        string `json:"field"`
	StartIndex   int64  `json:"startIndex"`
	EndIndex     int64  `json:"endIndex"`
	IdcSpecified string `json:"idcSpecified"`
}

func (st *GetRangeListReq) resetDefault() {
	st.IdcSpecified = ""
}

//ReadFrom reads  from _is and put into struct.
func (st *GetRangeListReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = _is.Read_string(&st.ModuleName, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.MainKey, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.Field, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_int64(&st.StartIndex, 4, true)
	if err != nil {
		return err
	}

	err = _is.Read_int64(&st.EndIndex, 5, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.IdcSpecified, 6, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *GetRangeListReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require GetRangeListReq, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *GetRangeListReq) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.Write_string(st.ModuleName, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.MainKey, 2)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.Field, 3)
	if err != nil {
		return err
	}

	err = _os.Write_int64(st.StartIndex, 4)
	if err != nil {
		return err
	}

	err = _os.Write_int64(st.EndIndex, 5)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.IdcSpecified, 6)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *GetRangeListReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
