//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//GetZsetByScoreReq strcut implement
type GetZsetByScoreReq struct {
	ModuleName   string  `json:"moduleName"`
	MainKey      string  `json:"mainKey"`
	Field        string  `json:"field"`
	MinScore     float64 `json:"minScore"`
	MaxScore     float64 `json:"maxScore"`
	IdcSpecified string  `json:"idcSpecified"`
}

func (st *GetZsetByScoreReq) resetDefault() {
	st.IdcSpecified = ""
}

//ReadFrom reads  from _is and put into struct.
func (st *GetZsetByScoreReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = _is.Read_string(&st.ModuleName, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.MainKey, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.Field, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_float64(&st.MinScore, 4, true)
	if err != nil {
		return err
	}

	err = _is.Read_float64(&st.MaxScore, 5, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.IdcSpecified, 6, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *GetZsetByScoreReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require GetZsetByScoreReq, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *GetZsetByScoreReq) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.Write_string(st.ModuleName, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.MainKey, 2)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.Field, 3)
	if err != nil {
		return err
	}

	err = _os.Write_float64(st.MinScore, 4)
	if err != nil {
		return err
	}

	err = _os.Write_float64(st.MaxScore, 5)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.IdcSpecified, 6)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *GetZsetByScoreReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
