//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//MainKeyValueBS strcut implement
type MainKeyValueBS struct {
	MainKey []int8              `json:"mainKey"`
	Value   []map[string][]int8 `json:"value"`
	Ret     int32               `json:"ret"`
}

func (st *MainKeyValueBS) resetDefault() {
}

//ReadFrom reads  from _is and put into struct.
func (st *MainKeyValueBS) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err, _, ty = _is.SkipToNoCheck(1, true)
	if err != nil {
		return err
	}

	if ty == codec.LIST {
		err = _is.Read_int32(&length, 0, true)
		if err != nil {
			return err
		}
		st.MainKey = make([]int8, length, length)
		for i0, e0 := int32(0), length; i0 < e0; i0++ {

			err = _is.Read_int8(&st.MainKey[i0], 0, false)
			if err != nil {
				return err
			}
		}
	} else if ty == codec.SIMPLE_LIST {

		err, _ = _is.SkipTo(codec.BYTE, 0, true)
		if err != nil {
			return err
		}
		err = _is.Read_int32(&length, 0, true)
		if err != nil {
			return err
		}
		err = _is.Read_slice_int8(&st.MainKey, length, true)
		if err != nil {
			return err
		}

	} else {
		err = fmt.Errorf("require vector, but not")
		if err != nil {
			return err
		}
	}

	err, _, ty = _is.SkipToNoCheck(2, true)
	if err != nil {
		return err
	}

	if ty == codec.LIST {
		err = _is.Read_int32(&length, 0, true)
		if err != nil {
			return err
		}
		st.Value = make([]map[string][]int8, length, length)
		for i1, e1 := int32(0), length; i1 < e1; i1++ {

			err, have = _is.SkipTo(codec.MAP, 0, false)
			if err != nil {
				return err
			}
			if have {
				err = _is.Read_int32(&length, 0, true)
				if err != nil {
					return err
				}
				st.Value[i1] = make(map[string][]int8)
				for i2, e2 := int32(0), length; i2 < e2; i2++ {
					var k2 string
					var v2 []int8

					err = _is.Read_string(&k2, 0, false)
					if err != nil {
						return err
					}

					err, have, ty = _is.SkipToNoCheck(1, false)
					if err != nil {
						return err
					}
					if have {
						if ty == codec.LIST {
							err = _is.Read_int32(&length, 0, true)
							if err != nil {
								return err
							}
							v2 = make([]int8, length, length)
							for i3, e3 := int32(0), length; i3 < e3; i3++ {

								err = _is.Read_int8(&v2[i3], 0, false)
								if err != nil {
									return err
								}
							}
						} else if ty == codec.SIMPLE_LIST {

							err, _ = _is.SkipTo(codec.BYTE, 0, true)
							if err != nil {
								return err
							}
							err = _is.Read_int32(&length, 0, true)
							if err != nil {
								return err
							}
							err = _is.Read_slice_int8(&v2, length, true)
							if err != nil {
								return err
							}

						} else {
							err = fmt.Errorf("require vector, but not")
							if err != nil {
								return err
							}
						}
					}

					st.Value[i1][k2] = v2
				}
			}
		}
	} else if ty == codec.SIMPLE_LIST {
		err = fmt.Errorf("not support simple_list type")
		if err != nil {
			return err
		}
	} else {
		err = fmt.Errorf("require vector, but not")
		if err != nil {
			return err
		}
	}

	err = _is.Read_int32(&st.Ret, 3, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *MainKeyValueBS) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require MainKeyValueBS, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *MainKeyValueBS) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.WriteHead(codec.SIMPLE_LIST, 1)
	if err != nil {
		return err
	}
	err = _os.WriteHead(codec.BYTE, 0)
	if err != nil {
		return err
	}
	err = _os.Write_int32(int32(len(st.MainKey)), 0)
	if err != nil {
		return err
	}
	err = _os.Write_slice_int8(st.MainKey)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.LIST, 2)
	if err != nil {
		return err
	}
	err = _os.Write_int32(int32(len(st.Value)), 0)
	if err != nil {
		return err
	}
	for _, v := range st.Value {

		err = _os.WriteHead(codec.MAP, 0)
		if err != nil {
			return err
		}
		err = _os.Write_int32(int32(len(v)), 0)
		if err != nil {
			return err
		}
		for k4, v4 := range v {

			err = _os.Write_string(k4, 0)
			if err != nil {
				return err
			}

			err = _os.WriteHead(codec.SIMPLE_LIST, 1)
			if err != nil {
				return err
			}
			err = _os.WriteHead(codec.BYTE, 0)
			if err != nil {
				return err
			}
			err = _os.Write_int32(int32(len(v4)), 0)
			if err != nil {
				return err
			}
			err = _os.Write_slice_int8(v4)
			if err != nil {
				return err
			}
		}
	}

	err = _os.Write_int32(st.Ret, 3)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *MainKeyValueBS) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
