//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

type Op int32

const (
	//Op_SET enum
	Op_SET = 0
	//Op_ADD enum
	Op_ADD = 1
	//Op_SUB enum
	Op_SUB = 2
	//Op_EQ enum
	Op_EQ = 3
	//Op_NE enum
	Op_NE = 4
	//Op_GT enum
	Op_GT = 5
	//Op_LT enum
	Op_LT = 6
	//Op_LE enum
	Op_LE = 7
	//Op_GE enum
	Op_GE = 8
	//Op_LIMIT enum
	Op_LIMIT = 9
	//Op_PREPEND enum
	Op_PREPEND = 10
	//Op_APPEND enum
	Op_APPEND = 11
	//Op_ADD_INSERT enum
	Op_ADD_INSERT = 12
	//Op_SUB_INSERT enum
	Op_SUB_INSERT = 13
)
