//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//SKeyValue strcut implement
type SKeyValue struct {
	KeyItem    string `json:"keyItem"`
	Value      string `json:"value"`
	Ret        int32  `json:"ret"`
	Ver        int8   `json:"ver"`
	ExpireTime int32  `json:"expireTime"`
}

func (st *SKeyValue) resetDefault() {
	st.ExpireTime = 0
}

//ReadFrom reads  from _is and put into struct.
func (st *SKeyValue) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = _is.Read_string(&st.KeyItem, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.Value, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.Ret, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_int8(&st.Ver, 4, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.ExpireTime, 5, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *SKeyValue) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require SKeyValue, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *SKeyValue) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.Write_string(st.KeyItem, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.Value, 2)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.Ret, 3)
	if err != nil {
		return err
	}

	err = _os.Write_int8(st.Ver, 4)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.ExpireTime, 5)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *SKeyValue) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
