//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//SSetKeyValue strcut implement
type SSetKeyValue struct {
	KeyItem          string `json:"keyItem"`
	Value            string `json:"value"`
	Version          int8   `json:"version"`
	Dirty            bool   `json:"dirty"`
	ExpireTimeSecond int32  `json:"expireTimeSecond"`
}

func (st *SSetKeyValue) resetDefault() {
	st.Version = 0
	st.Dirty = true
	st.ExpireTimeSecond = 0
}

//ReadFrom reads  from _is and put into struct.
func (st *SSetKeyValue) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = _is.Read_string(&st.KeyItem, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.Value, 2, true)
	if err != nil {
		return err
	}

	err = _is.Read_int8(&st.Version, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_bool(&st.Dirty, 4, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.ExpireTimeSecond, 5, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *SSetKeyValue) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require SSetKeyValue, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *SSetKeyValue) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.Write_string(st.KeyItem, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.Value, 2)
	if err != nil {
		return err
	}

	err = _os.Write_int8(st.Version, 3)
	if err != nil {
		return err
	}

	err = _os.Write_bool(st.Dirty, 4)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.ExpireTimeSecond, 5)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *SSetKeyValue) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
