//Package DCache comment
// This file war generated by tars2go 1.1
// Generated from ProxyShare.tars
package DCache

import (
	"fmt"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

//UpdateMKVAtomReq strcut implement
type UpdateMKVAtomReq struct {
	ModuleName       string                 `json:"moduleName"`
	MainKey          string                 `json:"mainKey"`
	Value            map[string]UpdateValue `json:"value"`
	Cond             []Condition            `json:"cond"`
	Dirty            bool                   `json:"dirty"`
	ExpireTimeSecond int32                  `json:"expireTimeSecond"`
}

func (st *UpdateMKVAtomReq) resetDefault() {
	st.Dirty = true
	st.ExpireTimeSecond = 0
}

//ReadFrom reads  from _is and put into struct.
func (st *UpdateMKVAtomReq) ReadFrom(_is *codec.Reader) error {
	var err error
	var length int32
	var have bool
	var ty byte
	st.resetDefault()

	err = _is.Read_string(&st.ModuleName, 1, true)
	if err != nil {
		return err
	}

	err = _is.Read_string(&st.MainKey, 2, true)
	if err != nil {
		return err
	}

	err, have = _is.SkipTo(codec.MAP, 3, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&length, 0, true)
	if err != nil {
		return err
	}
	st.Value = make(map[string]UpdateValue)
	for i0, e0 := int32(0), length; i0 < e0; i0++ {
		var k0 string
		var v0 UpdateValue

		err = _is.Read_string(&k0, 0, false)
		if err != nil {
			return err
		}

		err = v0.ReadBlock(_is, 1, false)
		if err != nil {
			return err
		}

		st.Value[k0] = v0
	}

	err, _, ty = _is.SkipToNoCheck(4, true)
	if err != nil {
		return err
	}

	if ty == codec.LIST {
		err = _is.Read_int32(&length, 0, true)
		if err != nil {
			return err
		}
		st.Cond = make([]Condition, length, length)
		for i1, e1 := int32(0), length; i1 < e1; i1++ {

			err = st.Cond[i1].ReadBlock(_is, 0, false)
			if err != nil {
				return err
			}
		}
	} else if ty == codec.SIMPLE_LIST {
		err = fmt.Errorf("not support simple_list type")
		if err != nil {
			return err
		}
	} else {
		err = fmt.Errorf("require vector, but not")
		if err != nil {
			return err
		}
	}

	err = _is.Read_bool(&st.Dirty, 5, true)
	if err != nil {
		return err
	}

	err = _is.Read_int32(&st.ExpireTimeSecond, 6, true)
	if err != nil {
		return err
	}

	_ = length
	_ = have
	_ = ty
	return nil
}

//ReadBlock reads struct from the given tag , require or optional.
func (st *UpdateMKVAtomReq) ReadBlock(_is *codec.Reader, tag byte, require bool) error {
	var err error
	var have bool
	st.resetDefault()

	err, have = _is.SkipTo(codec.STRUCT_BEGIN, tag, require)
	if err != nil {
		return err
	}
	if !have {
		if require {
			return fmt.Errorf("require UpdateMKVAtomReq, but not exist. tag %d", tag)
		}
		return nil

	}

	st.ReadFrom(_is)

	err = _is.SkipToStructEnd()
	if err != nil {
		return err
	}
	_ = have
	return nil
}

//WriteTo encode struct to buffer
func (st *UpdateMKVAtomReq) WriteTo(_os *codec.Buffer) error {
	var err error

	err = _os.Write_string(st.ModuleName, 1)
	if err != nil {
		return err
	}

	err = _os.Write_string(st.MainKey, 2)
	if err != nil {
		return err
	}

	err = _os.WriteHead(codec.MAP, 3)
	if err != nil {
		return err
	}
	err = _os.Write_int32(int32(len(st.Value)), 0)
	if err != nil {
		return err
	}
	for k2, v2 := range st.Value {

		err = _os.Write_string(k2, 0)
		if err != nil {
			return err
		}

		err = v2.WriteBlock(_os, 1)
		if err != nil {
			return err
		}
	}

	err = _os.WriteHead(codec.LIST, 4)
	if err != nil {
		return err
	}
	err = _os.Write_int32(int32(len(st.Cond)), 0)
	if err != nil {
		return err
	}
	for _, v := range st.Cond {

		err = v.WriteBlock(_os, 0)
		if err != nil {
			return err
		}
	}

	err = _os.Write_bool(st.Dirty, 5)
	if err != nil {
		return err
	}

	err = _os.Write_int32(st.ExpireTimeSecond, 6)
	if err != nil {
		return err
	}

	return nil
}

//WriteBlock encode struct
func (st *UpdateMKVAtomReq) WriteBlock(_os *codec.Buffer, tag byte) error {
	var err error
	err = _os.WriteHead(codec.STRUCT_BEGIN, tag)
	if err != nil {
		return err
	}

	st.WriteTo(_os)

	err = _os.WriteHead(codec.STRUCT_END, 0)
	if err != nil {
		return err
	}
	return nil
}
