Title = "DCache Configure"

[Registry]
Property = "tars.tarsregistry.QueryObj@tcp -h {{id_addr}} -p 17890"

[KVCache]
ModuleName = "DCacheApp_xxx"
CacheObj = "DCache.DCacheApp_xxxKVCacheServer1-1.CacheObj"
WCacheObj = "DCache.DCacheApp_xxxKVCacheServer1-1.WCacheObj"
